# Default values for undermoon-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  operatorImage: doyoubi/undermoon-operator
  operatorImageTag: v0.3.0
  operatorImagePullPolicy: IfNotPresent

broker_api_version: "v3"

nameOverride: ""
fullnameOverride: ""
