# permissions for end users to view undermoons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: undermoon-viewer-role
rules:
- apiGroups:
  - undermoon.doyoubi.mydomain
  resources:
  - undermoons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - undermoon.doyoubi.mydomain
  resources:
  - undermoons/status
  verbs:
  - get
