apiVersion: v1
kind: ConfigMap
metadata:
  name: undermoon-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  undermoon-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: undermoon-scheduler
      plugins:
        filter:
          enabled:
          - name: "undermoon-topology"
      pluginConfig:
      - name: "undermoon-topology"
