apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases

images:
- name: controller
  newName: "{{ .Values.image.operatorImage }}"
  newTag: "{{ .Values.image.operatorImageTag }}"

namespace: "{{ quote .Release.Namespace }}"

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: undermoon-operator
    namespace: system  # Need namespace here: https://github.com/kubernetes-sigs/kustomize/issues/1332#issuecomment-511180301
  path: replace_values.yaml
