apiVersion: v1
kind: Service
metadata:
  name: undermoon-operator-storage
  namespace: {{ quote .Release.Namespace }}
spec:
  ports:
  - port: 9999
    protocol: TCP
  selector:
    control-plane: undermoon-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: undermoon-operator
  name: undermoon-operator
  namespace: {{ quote .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: undermoon-operator
  template:
    metadata:
      labels:
        control-plane: undermoon-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: GIN_MODE
          value: release
        - name: UNDERMOON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UNDERMOON_OPERATOR_BROKER_API_VERSION
          value: {{ .Values.broker_api_version | default "v3" | quote }}
        image: {{ .Values.image.operatorImage }}:{{ .Values.image.operatorImageTag }}
        imagePullPolicy: {{ quote .Values.image.operatorImagePullPolicy }}
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
