apiVersion: v1
kind: Service
metadata:
  name: undermoon-operator-storage
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 9999
    protocol: TCP
  selector:
    control-plane: undermoon-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: undermoon-operator
  name: undermoon-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: undermoon-operator
  template:
    metadata:
      labels:
        control-plane: undermoon-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: GIN_MODE
          value: release
        image: '{{ .Values.image.operatorImage }}:{{ .Values.image.operatorImageTag }}'
        imagePullPolicy: '{{ .Values.image.operatorImagePullPolicy }}'
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
