apiVersion: apps/v1
kind: Deployment
metadata:
  name: undermoon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: undermoon-operator
  template:
    metadata:
      labels:
        name: undermoon-operator
    spec:
      serviceAccountName: undermoon-operator
      containers:
        - name: "{{ include "undermoon-operator.fullname" . }}"
          image: "{{ .Values.image.operatorImage }}"
          command:
          - undermoon-operator
          imagePullPolicy: "{{ .Values.image.operatorImagePullPolicy }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "undermoon-operator"
