# The generated `metadata` of pvc does not contain the `name` property.
# We need to add them manually.
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/volumeClaimTemplates/items/properties/metadata/properties
  value:
    name:
      type: string
