apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

patchesJson6902:
- target:
    group: undermoon.doyoubi.mydomain
    version: v1alpha1
    kind: Undermoon
    name: undermoon-sample
  path: replace_value.yaml