apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

namePrefix: undermoon-operator-
namespace: "{{ quote .Release.Namespace }}"

patchesJson6902:
- target:
    group: undermoon.doyoubi.mydomain
    version: v1alpha1
    kind: Undermoon
    name: example-undermoon
  path: replace_values.yaml