# `make update-types` will strip the '"' to support non-string type.
- op: replace
  path: /metadata/name
  value: '{{ include "undermoon-cluster.fullname" . }}'
- op: replace
  path: /spec/clusterName
  value: "{{ .Values.cluster.clusterName }}"
- op: replace
  path: /spec/chunkNumber
  value: "{{ .Values.cluster.chunkNumber }}"
- op: replace
  path: /spec/maxMemory
  value: "{{ .Values.cluster.maxMemory }}"
- op: replace
  path: /spec/port
  value: "{{ .Values.cluster.port }}"
- op: replace
  path: /spec/activeRedirection
  value: "{{ .Values.cluster.activeRedirection }}"
- op: replace
  path: /spec/proxyThreads
  value: "{{ .Values.cluster.proxyThreads }}"
- op: replace
  path: /spec/migrationScanInterval
  value: "{{ .Values.cluster.migrationScanInterval }}"
- op: replace
  path: /spec/migrationScanCount
  value: "{{ .Values.cluster.migrationScanCount }}"
- op: replace
  path: /spec/disableFailover
  value: "{{ .Values.cluster.disableFailover }}"
- op: replace
  path: /spec/undermoonImage
  value: "{{ .Values.image.undermoonImage }}:{{ .Values.image.undermoonImageTag }}"
- op: replace
  path: /spec/undermoonImagePullPolicy
  value: "{{ .Values.image.undermoonImagePullPolicy }}"
- op: replace
  path: /spec/redisImage
  value: "{{ .Values.image.redisImage }}:{{ .Values.image.redisImageTag }}"
- op: replace
  path: /spec/brokerResources
  value: "{{- toYaml .Values.resources.brokerResources | nindent 4 }}"
- op: replace
  path: /spec/coordinatorResources
  value: "{{- toYaml .Values.resources.coordinatorResources | nindent 4 }}"
- op: replace
  path: /spec/proxyResources
  value: "{{- toYaml .Values.resources.proxyResources | nindent 4 }}"
- op: replace
  path: /spec/redisResources
  value: "{{- toYaml .Values.resources.redisResources | nindent 4 }}"
- op: replace
  path: /spec/affinity
  value: "{{- toYaml .Values.affinity | nindent 4 }}"
- op: replace
  path: /spec/nodeSelector
  value: "{{- toYaml .Values.nodeSelector | nindent 4 }}"
- op: replace
  path: /spec/imagePullSecrets
  value: "{{- toYaml .Values.imagePullSecrets | nindent 4 }}"
- op: replace
  path: /spec/schedulerName
  value: "{{ quote .Values.schedulerName }}"
- op: replace
  path: /spec/tolerations
  value: "{{- toYaml .Values.tolerations | nindent 4 }}"
- op: replace
  path: /spec/storageVolumes
  value: "{{- toYaml .Values.storageVolumes | nindent 4 }}"
- op: replace
  path: /spec/redisVolumeMounts
  value: "{{- toYaml .Values.redisVolumeMounts | nindent 4 }}"
- op: replace
  path: /spec/redisVolumeDevices
  value: "{{- toYaml .Values.redisVolumeDevices | nindent 4 }}"
- op: replace
  path: /spec/volumeClaimTemplates
  value: "{{- toYaml .Values.volumeClaimTemplates | nindent 4 }}"
