# Default values for undermoon-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster:
  clusterName: example-undermoon
  chunkNumber: 1
  maxMemory: 32  # in MBs
  port: 5299
  activeRedirection: false
  proxyThreads: 4
  migrationScanInterval: 1000
  migrationScanCount: 16

image:
  undermoonImage: doyoubi/undermoon
  undermoonImageTag: 0.4.1-buster
  undermoonImagePullPolicy: IfNotPresent
  redisImage: redis
  redisImageTag: 5.0.9

resources:
  brokerResources:
    limits:
      {}
      # memory: "1G"
  coordinatorResources:
    limits:
      {}
      # memory: "1G"
  proxyResources:
    limits:
      {}
      # memory: "1G"
  redisResources:
    limits:
      {}
      # memory: "5G"

affinity: {}

nameOverride: ""
fullnameOverride: ""
