apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "undermoon-checker.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "undermoon-checker.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "undermoon-checker.fullname" . }}
    spec:
      containers:
        - name: {{ include "undermoon-checker.name" . }}
          image: "{{ .Values.image.checkerImage }}"
          imagePullPolicy: {{ .Values.image.checkerImagePullPolicy }}
          command:
          {{- if .Values.golangChecker }}
          - checker
          - --address
          - "{{ .Values.undermoonServiceAddress }}"
          - --ops
          - "{{ .Values.ops }}"
          - --block-on-error
          {{- else }}
          - python
          - {{ include "undermoon-checker.test_script" . }}
          - "{{ .Values.undermoonServiceAddress }}"
          {{- end }}
          # For debugging
          # - sleep
          # - "10000000"