# We don't need to create namespace.
#
# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     control-plane: undermoon-operator
#   name: system
# ---
# This Service is used to expose an storage api to broker.
apiVersion: v1
kind: Service
metadata:
  name: undermoon-operator-storage
spec:
  selector:
    control-plane: undermoon-operator
  ports:
    - protocol: TCP
      port: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undermoon-operator
  namespace: system
  labels:
    control-plane: undermoon-operator
spec:
  selector:
    matchLabels:
      control-plane: undermoon-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: undermoon-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        env:
        - name: GIN_MODE
          value: "release"
        - name: UNDERMOON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UNDERMOON_OPERATOR_BROKER_API_VERSION
          value: '{{ .Values.broker_api_version | default "v2" }}'
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
